function formalismList = read_formalisms(databaseName)
% formalismList = read_formalisms(databaseName)
%   Unified function returning lists of all available formalisms for different
%   spectroscopy calculations.
%
%   IN:
%   -   databaseName: string specifying the formalism category
%               Options: 'auger'  : Auger electron spectroscopy transition energies
%                        'be'     : X-ray photoelectron spectroscopy binding energies
%                        'imfp'   : Inelastic mean free path for electron transport
%                        'xae'    : X-ray absorption edge energies and linewidths
%                        'xasf'   : X-ray atomic scattering factors for X-ray diffraction
%                        'xsect'  : Photoionization cross-sections
%
%   OUT:
%   -   formalismList: 1xN cell array of available databases for the specified database

%% Validate input
arguments
    databaseName (1,:) char {mustBeMember(databaseName,...
        {'auger', 'be', 'imfp', 'xae', 'xasf', 'xsect', 'xsect-angleaniso'})}
end
%% 1 - Return list of relevant formalism
switch databaseName
    % Auger transition energies used for element identification
    case "auger"
        formalismList = {...
            "Perkins(1991)"...
            };
    % Core-level photoionization / binding energy datasets
    case "be"
        formalismList = {...
            "Constantinou(2023)",...
            "Cant(2022)",...
            "Trzhaskovskaya(2018)",...
            "Moulder(1993)"...
        };
    % Electron attenuation lengths (IMFP / EAL) for quantitative XPS
    case "imfp"
        formalismList = {...
            "JTP(2023)",...
            "S4(2012)",...
            "S3O(2012)",...
            "S3(2012)",...
            "S2(2011)",...
            "S1(2011)",...
            "NIST(1999)",...
            "TPP2M-avg(1994)",...
            "TPP2M(1994)",...
            "Universal(1979)"
        };
    % Absorption edge energies, widths and jump ratios
    case "xae"
        formalismList = {...
            "IXAS(2025)"...
            };
    % Atomic scattering factors for X-ray diffraction / scattering
    case "xasf"
        formalismList = {...
            "NIST(2005)",...
            "Henke(1993)"
        };
    % Energy-dependent photoionization / absorption cross-sections
    case "xsect"
        formalismList = {...
            "Cant(2022)",...
            "Trzhaskovskaya(2018)",...
            "YehLindau(1985)",...
            "Scofield(1973)"...
        };
    % Angle Anisotropy of Photoionization Cross-Sections
    case "xsect-angleaniso"
        formalismList = {...
            "Cant(2022) - Partially Polarized Light (FP)",...
            "Cant(2022) - Linearly Polarized Light (FL)",...
            "Cant(2022) - Unpolarized Light (FU)"...
            "YehLindau(1985) - Linearly Polarized Light (Fadj)",...
        };
end
end